# Generated by Django 2.1 on 2018-08-31 01:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('photoUrl', models.CharField(default='', max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('treatment', models.CharField(default='', max_length=500)),
                ('reviewed', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
