# Generated by Django 2.1 on 2018-08-31 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='lat',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='incident',
            name='lon',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='incident',
            name='photoUrl',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='incident',
            name='treatment',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
