# Generated by Django 2.1 on 2018-08-31 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpi', '0002_auto_20180831_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('url', models.CharField(blank=True, default='', max_length=500)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
