# Generated by Django 2.1 on 2018-08-31 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpi', '0004_auto_20180831_1556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incident',
            old_name='reviewed',
            new_name='alert',
        ),
        migrations.AddField(
            model_name='incident',
            name='zipcode',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
